version: 2.1

defaults: &defaults
  docker:
    - image: cimg/node:18.5
  working_directory: ~/{{ name }}

jobs:
  lint:
    <<: *defaults
    steps:
      - checkout
      - run: npm ci
      - run: npm run lint
  test:
    <<: *defaults
    steps:
      - checkout
      - run: npm ci
      - run: npm run test -- --coverage
      - store_test_results:
          path: reports/jest/
      - store_artifacts:
          path: reports/

workflows:
  version: 2
  test:
    jobs:
      - lint:
          name: Lint
          context: nodejs-install
      - test:
          name: Test
          context: nodejs-install
