version: 2.1
defaults: &defaults
  working_directory: ~/test
  resource_class: small
  docker:
    - image: robcresswell/circleci-node-alpine
commands:
  install_deps:
    description: Install dependencies
    steps:
      - checkout
      - restore_cache:
          keys:
            # when lock file changes, use increasingly general patterns to restore cache
            - yarn-{{ checksum "yarn.lock" }}
            - yarn-
      - run: yarn --frozen-lockfile
      - save_cache:
          paths:
            - ~/.cache/yarn
          key: yarn-{{ checksum "yarn.lock" }}
jobs:
  test:
    <<: *defaults
    steps:
      - install_deps
      - run: yarn test:coverage
      - store_artifacts:
          path: reports
      - store_test_results:
          path: reports
  lint:
    <<: *defaults
    steps:
      - install_deps
      - run: yarn lint
  security:
    <<: *defaults
    steps:
      - checkout
      - run: npx snyk test
  build:
    <<: *defaults
    steps:
      - install_deps
      - run: yarn build
  release:
    <<: *defaults
    steps:
      - install_deps
      - run: yarn build
      - run: npx semantic-release --dry-run
workflows:
  version: 2
  test_and_release:
    jobs:
      - lint:
          name: Lint
      - build:
          name: Build
      - security:
          name: Snyk
      - test:
          name: Test
          requires:
            - Lint
            - Build
            - Snyk
      - release:
          name: Release
          requires:
            - Test
          filters:
            branches:
              only:
                - dev
